export const mockCases = [
  {
    id: "case-1",
    patientName: "Rajesh Kumar",
    patientInitial: "R",
    condition: "Tinea Corporis",
    aiConfidence: 92,
    severity: 3,
    type: "Fungal",
    submittedDate: "2026-03-30",
    photos: ["photo1", "photo2", "photo3"],
    bodyLocation: "Chest",
    patientAge: 35,
    flagged: false,
  },
  {
    id: "case-2",
    patientName: "Priya Sharma",
    patientInitial: "P",
    condition: "Eczema",
    aiConfidence: 87,
    severity: 2,
    type: "Bacterial",
    submittedDate: "2026-03-30",
    photos: ["photo1", "photo2"],
    bodyLocation: "Forearm",
    patientAge: 28,
    flagged: false,
  },
  {
    id: "case-3",
    patientName: "Amit Patel",
    patientInitial: "A",
    condition: "Acne Vulgaris",
    aiConfidence: 78,
    severity: 2,
    type: "Complex",
    submittedDate: "2026-03-29",
    photos: ["photo1"],
    bodyLocation: "Face",
    patientAge: 22,
    flagged: true,
  },
  {
    id: "case-4",
    patientName: "Sneha Gupta",
    patientInitial: "S",
    condition: "Psoriasis",
    aiConfidence: 85,
    severity: 3,
    type: "Viral",
    submittedDate: "2026-03-29",
    photos: ["photo1", "photo2", "photo3", "photo4"],
    bodyLocation: "Scalp",
    patientAge: 45,
    flagged: false,
  },
  {
    id: "case-5",
    patientName: "Vikram Singh",
    patientInitial: "V",
    condition: "Contact Dermatitis",
    aiConfidence: 81,
    severity: 2,
    type: "Fungal",
    submittedDate: "2026-03-28",
    photos: ["photo1", "photo2"],
    bodyLocation: "Hand",
    patientAge: 38,
    flagged: false,
  },
  {
    id: "case-6",
    patientName: "Divya Nair",
    patientInitial: "D",
    condition: "Tinea Pedis",
    aiConfidence: 89,
    severity: 2,
    type: "Fungal",
    submittedDate: "2026-03-28",
    photos: ["photo1", "photo2", "photo3"],
    bodyLocation: "Foot",
    patientAge: 52,
    flagged: false,
  },
  {
    id: "case-7",
    patientName: "Arjun Verma",
    patientInitial: "A",
    condition: "Bacterial Infection",
    aiConfidence: 76,
    severity: 3,
    type: "Bacterial",
    submittedDate: "2026-03-28",
    photos: ["photo1", "photo2"],
    bodyLocation: "Leg",
    patientAge: 33,
    flagged: true,
  },
  {
    id: "case-8",
    patientName: "Neha Singh",
    patientInitial: "N",
    condition: "Urticaria",
    aiConfidence: 83,
    severity: 2,
    type: "Complex",
    submittedDate: "2026-03-27",
    photos: ["photo1"],
    bodyLocation: "Full Body",
    patientAge: 29,
    flagged: false,
  },
  {
    id: "case-9",
    patientName: "Sanjay Das",
    patientInitial: "S",
    condition: "Melasma",
    aiConfidence: 88,
    severity: 2,
    type: "Complex",
    submittedDate: "2026-03-27",
    photos: ["photo1", "photo2"],
    bodyLocation: "Face",
    patientAge: 41,
    flagged: false,
  },
  {
    id: "case-10",
    patientName: "Kavya Desai",
    patientInitial: "K",
    condition: "Hair Loss",
    aiConfidence: 79,
    severity: 3,
    type: "Viral",
    submittedDate: "2026-03-27",
    photos: ["photo1", "photo2", "photo3"],
    bodyLocation: "Scalp",
    patientAge: 35,
    flagged: false,
  },
  {
    id: "case-11",
    patientName: "Rohan Chopra",
    patientInitial: "R",
    condition: "Warts",
    aiConfidence: 86,
    severity: 1,
    type: "Viral",
    submittedDate: "2026-03-26",
    photos: ["photo1", "photo2"],
    bodyLocation: "Hand",
    patientAge: 25,
    flagged: false,
  },
  {
    id: "case-12",
    patientName: "Ananya Reddy",
    patientInitial: "A",
    condition: "Vitiligo",
    aiConfidence: 82,
    severity: 2,
    type: "Complex",
    submittedDate: "2026-03-26",
    photos: ["photo1", "photo2", "photo3"],
    bodyLocation: "Hands & Face",
    patientAge: 31,
    flagged: false,
  },
];

export const mockPatients = [
  {
    id: "patient-1",
    name: "Rajesh Kumar",
    linkedDate: "2025-10-15",
    condition: "Tinea Corporis",
    lastPhotoDate: "2026-03-30",
    treatmentProgress: 65,
    photos: [
      { date: "2026-03-15", progress: 30 },
      { date: "2026-03-22", progress: 50 },
      { date: "2026-03-30", progress: 65 },
    ],
    prescriptions: [
      { date: "2025-10-20", condition: "Tinea Corporis", template: "tinea-corporis" },
    ],
  },
  {
    id: "patient-2",
    name: "Priya Sharma",
    linkedDate: "2025-11-20",
    condition: "Eczema",
    lastPhotoDate: "2026-03-28",
    treatmentProgress: 45,
    photos: [
      { date: "2026-02-15", progress: 20 },
      { date: "2026-03-15", progress: 35 },
      { date: "2026-03-28", progress: 45 },
    ],
    prescriptions: [
      { date: "2025-11-25", condition: "Eczema", template: "eczema" },
    ],
  },
  {
    id: "patient-3",
    name: "Amit Patel",
    linkedDate: "2026-01-10",
    condition: "Acne Vulgaris",
    lastPhotoDate: "2026-03-29",
    treatmentProgress: 55,
    photos: [
      { date: "2026-02-01", progress: 25 },
      { date: "2026-03-01", progress: 40 },
      { date: "2026-03-29", progress: 55 },
    ],
    prescriptions: [
      { date: "2026-01-15", condition: "Acne Vulgaris", template: "acne-vulgaris" },
    ],
  },
  {
    id: "patient-4",
    name: "Sneha Gupta",
    linkedDate: "2025-09-05",
    condition: "Psoriasis",
    lastPhotoDate: "2026-03-30",
    treatmentProgress: 72,
    photos: [
      { date: "2026-01-15", progress: 40 },
      { date: "2026-02-15", progress: 55 },
      { date: "2026-03-15", progress: 68 },
      { date: "2026-03-30", progress: 72 },
    ],
    prescriptions: [
      { date: "2025-09-10", condition: "Psoriasis", template: "psoriasis" },
      { date: "2026-02-01", condition: "Psoriasis (Follow-up)", template: "psoriasis" },
    ],
  },
  {
    id: "patient-5",
    name: "Vikram Singh",
    linkedDate: "2025-12-15",
    condition: "Contact Dermatitis",
    lastPhotoDate: "2026-03-25",
    treatmentProgress: 80,
    photos: [
      { date: "2026-01-15", progress: 30 },
      { date: "2026-02-20", progress: 60 },
      { date: "2026-03-25", progress: 80 },
    ],
    prescriptions: [
      { date: "2025-12-20", condition: "Contact Dermatitis", template: "contact-dermatitis" },
    ],
  },
  {
    id: "patient-6",
    name: "Divya Nair",
    linkedDate: "2026-02-01",
    condition: "Tinea Pedis",
    lastPhotoDate: "2026-03-26",
    treatmentProgress: 50,
    photos: [
      { date: "2026-02-15", progress: 20 },
      { date: "2026-03-15", progress: 35 },
      { date: "2026-03-26", progress: 50 },
    ],
    prescriptions: [
      { date: "2026-02-05", condition: "Tinea Pedis", template: "tinea-corporis" },
    ],
  },
  {
    id: "patient-7",
    name: "Arjun Verma",
    linkedDate: "2025-08-20",
    condition: "Bacterial Infection",
    lastPhotoDate: "2026-03-24",
    treatmentProgress: 88,
    photos: [
      { date: "2025-12-01", progress: 50 },
      { date: "2026-01-20", progress: 70 },
      { date: "2026-03-24", progress: 88 },
    ],
    prescriptions: [
      { date: "2025-08-25", condition: "Bacterial Infection", template: "contact-dermatitis" },
    ],
  },
  {
    id: "patient-8",
    name: "Neha Singh",
    linkedDate: "2026-03-01",
    condition: "Urticaria",
    lastPhotoDate: "2026-03-20",
    treatmentProgress: 60,
    photos: [
      { date: "2026-03-05", progress: 25 },
      { date: "2026-03-12", progress: 45 },
      { date: "2026-03-20", progress: 60 },
    ],
    prescriptions: [
      { date: "2026-03-02", condition: "Urticaria", template: "eczema" },
    ],
  },
  {
    id: "patient-9",
    name: "Kavya Desai",
    linkedDate: "2025-10-25",
    condition: "Hair Loss",
    lastPhotoDate: "2026-03-22",
    treatmentProgress: 35,
    photos: [
      { date: "2026-01-15", progress: 10 },
      { date: "2026-02-15", progress: 20 },
      { date: "2026-03-22", progress: 35 },
    ],
    prescriptions: [
      { date: "2025-10-30", condition: "Hair Loss", template: "tinea-corporis" },
    ],
  },
  {
    id: "patient-10",
    name: "Sanjay Das",
    linkedDate: "2025-11-10",
    condition: "Melasma",
    lastPhotoDate: "2026-03-28",
    treatmentProgress: 42,
    photos: [
      { date: "2026-01-20", progress: 15 },
      { date: "2026-02-28", progress: 30 },
      { date: "2026-03-28", progress: 42 },
    ],
    prescriptions: [
      { date: "2025-11-15", condition: "Melasma", template: "acne-vulgaris" },
    ],
  },
];

export const mockAppointments = [
  {
    id: "apt-1",
    patientName: "Rajesh Kumar",
    date: "2026-04-05",
    time: "10:00 AM",
    type: "Follow-up",
    status: "Scheduled",
  },
  {
    id: "apt-2",
    patientName: "Priya Sharma",
    date: "2026-04-06",
    time: "2:30 PM",
    type: "Initial Consultation",
    status: "Scheduled",
  },
  {
    id: "apt-3",
    patientName: "Amit Patel",
    date: "2026-04-08",
    time: "11:00 AM",
    type: "Follow-up",
    status: "Scheduled",
  },
  {
    id: "apt-4",
    patientName: "Sneha Gupta",
    date: "2026-04-10",
    time: "3:00 PM",
    type: "Final Review",
    status: "Scheduled",
  },
  {
    id: "apt-5",
    patientName: "Vikram Singh",
    date: "2026-04-12",
    time: "9:30 AM",
    type: "Follow-up",
    status: "Scheduled",
  },
];

export const mockAnalytics = {
  totalPatients: 127,
  casesReviewedThisMonth: 42,
  casesApprovedThisMonth: 38,
  averageConsultTime: 12.5,
  patientsCured: 89,
  patientsOngoing: 38,
  monthlyEarnings: 7600,
  dailyAverageEarnings: 250,
};

export const monthlyEarningsData = [
  { month: "Jan", earnings: 4200 },
  { month: "Feb", earnings: 5800 },
  { month: "Mar", earnings: 6400 },
  { month: "Apr", earnings: 5200 },
  { month: "May", earnings: 7100 },
  { month: "Jun", earnings: 8500 },
  { month: "Jul", earnings: 9200 },
];

export const doctorProfile = {
  name: "Dr. Priya Sharma",
  email: "dr.priya@tvachaclinic.com",
  phone: "+91 98765 43210",
  qualifications: "MBBS, MD (Dermatology)",
  registrationNumber: "MCI/2010-0245",
  clinicName: "Derma Care Clinic",
  clinicAddress: "123 Medical Plaza, Mumbai, India",
  referralCode: "DRPRIYA2026",
  subscriptionStatus: "Active",
  subscriptionPlan: "Professional",
  subscriptionRenewalDate: "2026-04-15",
};
